language: go

go:
 - 1.1
 - 1.2

install:
 - echo "Luckily, there are no dependencies"

script:
 - export GOPATH=$(pwd):$GOPATH
 - go test bitbucket.org/ww/goautoneg bitwrk/... chunking/...
 - go install ./src/cmd/bitwrk-client/ && bin/bitwrk-client --help || [ $? -eq 2 ]
