application: bitwrk
version: 1
runtime: go
api_version: go1

automatic_scaling:
  max_concurrent_requests: 200
  
handlers:
- url: /js
  static_dir: js
  
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  
- url: /.*
  script: _go_app
